# Generated by Django 4.1.7 on 2023-03-19 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_team_user_teams"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="teams",
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
