# Generated by Django 4.1.7 on 2023-03-19 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="team",
        ),
    ]
